# Generated by Django 2.1 on 2019-05-19 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyTiecCuoi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 19, 20, 8, 24, 639072)),
        ),
    ]
