# Generated by Django 2.1 on 2019-05-19 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyTiecCuoi', '0002_auto_20190519_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='address',
        ),
        migrations.RemoveField(
            model_name='room',
            name='email',
        ),
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 19, 20, 55, 30, 492442)),
        ),
    ]
